//* ========== Instance parameters for DMAC peripheral ========== */
const
  DMAC_CH_BITS               = 3;        // Number of bits to select channel
  DMAC_CH_NUM                = 6;        // Number of channels
  DMAC_CLK_AHB_ID            = 5;        // AHB clock index
  DMAC_EVIN_NUM              = 4;        // Number of input events
  DMAC_EVOUT_NUM             = 4;        // Number of output events
  DMAC_LVL_BITS              = 2;        // Number of bit to select level priority
  DMAC_LVL_NUM               = 4;        // Enable priority level number
  DMAC_TRIG_BITS             = 5;        // Number of bits to select trigger source
  DMAC_TRIG_NUM              = 20;       // Number of peripheral triggers
