//* ========== Instance parameters for AC peripheral ========== */
const
  AC_CMP_NUM                 = 2;        // Number of comparators
  AC_GCLK_ID_ANA             = 21;       // Index of Generic Clock for analog
  AC_GCLK_ID_DIG             = 20;       // Index of Generic Clock for digital
  AC_NUM_CMP                 = 2;
  AC_PAIRS                   = 1;        // Number of pairs of comparators
