//* ========== Instance parameters for RTC peripheral ========== */
const
  RTC_ALARM_NUM              = 1;        // Number of Alarms
  RTC_COMP16_NUM             = 2;        // Number of 16-bit Comparators
  RTC_COMP32_NUM             = 1;        // Number of 32-bit Comparators
  RTC_GCLK_ID                = 4;        // Index of Generic Clock
  RTC_NUM_OF_ALARMS          = 1;        // Number of Alarms (obsolete)
  RTC_NUM_OF_COMP16          = 2;        // Number of 16-bit Comparators (obsolete)
  RTC_NUM_OF_COMP32          = 1;        // Number of 32-bit Comparators (obsolete)
