//* ========== Instance parameters for SBMATRIX peripheral ========== */
const
//SBMATRIX_DEFINED

//* ========== Instance parameters for SBMATRIX ========== */
  SBMATRIX_SLAVE_FLASH         = 0;
  SBMATRIX_SLAVE_HPB0          = 1;
  SBMATRIX_SLAVE_HPB1          = 2;
  SBMATRIX_SLAVE_HPB2          = 3;
  SBMATRIX_SLAVE_HMCRAMC0      = 4;
  SBMATRIX_SLAVE_HMCRAMC0_ALT0 = 5;
  SBMATRIX_SLAVE_HMCRAMC0_ALT1 = 6;
  SBMATRIX_SLAVE_NUM           = 7;

  SBMATRIX_MASTER_CM0PLUS      = 0;
  SBMATRIX_MASTER_DSU          = 1;
  SBMATRIX_MASTER_DMAC         = 2;
  SBMATRIX_MASTER_NUM          = 3;
